# Generated by Django 5.1.4 on 2024-12-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='games',
        ),
    ]
