# Generated by Django 5.1.4 on 2025-02-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
    ]
